name: perseus_front_mobile
description: Perseus's mobile front
version: 1.0.5+8
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  badges: ^2.0.2
  bloc: ^8.0.3
  cupertino_icons: ^1.0.5
  dio: ^4.0.6
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_datetime_picker: ^1.5.1
  flutter_dotenv: ^5.0.2
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^5.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^0.13.4
  intl: ^0.17.0
  jwt_decoder: ^2.0.1
  sentry_flutter: ^6.5.1
  shared_preferences: ^2.0.13
  socket_io_client: ^1.0.2
  table_calendar: ^3.0.5
  url_launcher: ^6.1.4

dev_dependencies:
  bloc_test: ^9.0.3
  build_runner: ^2.1.11
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.3
  mocktail: ^0.3.0
  very_good_analysis: ^2.4.0

flutter:
  uses-material-design: true
  generate: true
  assets:     
    - assets/images/
    - .env